spring.application.name=gasModule
server.port=22411

spring.profiles.active=local

# --- JPA ---
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.devtools.restart.enabled=false
