# --- MSSQL ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.datasource.mssql.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.mssql.url=jdbc:sqlserver://your-mssql-host:1433;databaseName=YourDB
spring.datasource.mssql.username=your_username
spring.datasource.mssql.password=your_password

# --- POSTGRES ---
spring.datasource.postgres.driver-class-name=org.postgresql.Driver
spring.datasource.postgres.url=jdbc:postgresql://localhost:5432/your_database
spring.datasource.postgres.username=your_username
spring.datasource.postgres.password=your_password

# --- Gas Module ---
gas.polling.start-date=20251101000000
